/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import controllers.HomeController;
import spark.Request;
import spark.Response;
import spark.template.thymeleaf.ThymeleafTemplateEngine;

import static spark.Spark.get;
import static spark.Spark.staticFileLocation;


public class App {

    public static void main(String[] args) {
        staticFileLocation("/public");

        get("/", HomeController::get, new ThymeleafTemplateEngine());
    }

    public static String helloWorld(Request req, Response res) {
        return "hello world!";
    }
}
